version: "3.8"

services:
  # PHP + Laravel
  app:
    container_name: ${APP_NAME}-app
    restart: unless-stopped
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    volumes:
      - .:/var/www/html
      - ./docker/app/conf/php-fpm.conf:/etc/php-fpm.conf
      - ./docker/app/conf/php-app.ini:/usr/local/etc/php/conf.d/app.ini
      - ./docker/app/conf/supervisord.conf:/etc/supervisord.conf
      - ./docker/app/conf/queue.conf:/etc/supervisord.d/queue.conf
    networks:
      - mynetwork

  # Nginx
  nginx:
    container_name: ${APP_NAME}-nginx
    restart: unless-stopped
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - ${APP_PORT_DOCKER}:80
    volumes:
      - .:/var/www/html
      - ./docker/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/conf/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - mynetwork
    depends_on:
      - app

  # DB
  db:
    image: mysql:8.0
    container_name: ${APP_NAME}-db
    volumes:
      - ./docker/data/mysql:/var/lib/mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${DB_PORT_DOCKER}:${DB_PORT}
    networks:
      - mynetwork

networks:
  mynetwork:
    name: ${APP_NAME}-network
    driver: bridge
